version: '3.8'

services:
  monero-miner:
    image: monero-miner
    build: .
    environment:
      WALLET: 49NzKLonRimMhGnEiLNeZMTRFhNaVpPHoDrBUKiUsiDDXqXa6rbx7kagHQUNvEF8CfGjMD8KmKjBb7L6ZaEcRV9p5EZb32f
      POOL: pool.supportxmr.com:3333
      PASS: LocalDocker
      DONATE_LEVEL: 1
    privileged: true