networks:
  p2pool:
    driver: bridge

volumes:
  p2pool:
    name: p2pool
  monero:
    name: monero

services:
  p2pool:
    image: p2pool:latest
    build:
      context: p2pool/.
      args:
        - P2POOL_GIT_TAG=v4.1
    container_name: p2pool-p2pool
    networks:
      - p2pool
    privileged: true
    ports:
      - 37888:37888/tcp
      - 3333:3333/tcp
    volumes:
      - p2pool:/home/p2pool/.p2pool:rw
      - /dev/null:/home/p2pool/.p2pool/p2pool.log:rw
      - /dev/hugepages:/dev/hugepages:rw
    depends_on:
      - monero
    restart: unless-stopped
    healthcheck:
      test: >-
        curl -X GET http://localhost:3333 > /dev/null 2>&1 &&
        nc -zv localhost 37888 > /dev/null 2>&1 || exit 1
      interval: 10s
      retries: 3
      start_period: 20s
      timeout: 5s
    command: >-
      --host monero
      --wallet 49NzKLonRimMhGnEiLNeZMTRFhNaVpPHoDrBUKiUsiDDXqXa6rbx7kagHQUNvEF8CfGjMD8KmKjBb7L6ZaEcRV9p5EZb32f
      --loglevel 3
      --local-api
      --data-api /home/p2pool/.p2pool
      --mini

  statistics:
    image: statistics:latest
    build:
      context: statistics
    container_name: p2pool-statistics
    networks:
      - p2pool
    ports:
      - 3380:3380/tcp
    volumes:
      - p2pool:/data:ro
    depends_on:
      - p2pool
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:3380/ || exit 1
      interval: 10s
      retries: 3
      start_period: 20s
      timeout: 5s

  monero:
    image: monero:latest
    build:
      context: monero
      args:
        - MONERO_GIT_TAG=v0.18.3.4
    container_name: p2pool-monero
    networks:
      - p2pool
    ports:
      - 18080:18080/tcp
    volumes:
      - monero:/home/monero/.bitmonero:rw
      - /dev/null:/home/monero/.bitmonero/bitmonero.log:rw
      - /dev/hugepages:/dev/hugepages:rw
    restart: on-failure:5
    healthcheck:
      test: >-
        curl -X POST http://localhost:18081/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_info"}' -H 'Content-Type: application/json' &&
        pgrep monerod > /dev/null && exit 0 || exit 1
      interval: 60s
      retries: 3
      start_period: 60s
      timeout: 5s
    command: >-
      --zmq-pub tcp://0.0.0.0:18083
      --disable-dns-checkpoints
      --enable-dns-blocklist
      --out-peers 16
      --in-peers 32
      --add-priority-node=nodes.hashvault.pro:18080
      --add-priority-node=p2pmd.xmrvsbeast.com:18080
      --non-interactive
      --p2p-bind-ip=0.0.0.0
      --p2p-bind-port=18080
      --rpc-bind-ip=0.0.0.0
      --rpc-bind-port=18081
      --restricted-rpc
      --confirm-external-bind
      --log-level=0
      --prune-blockchain
      --fast-block-sync=1

  xmrig:
    image: xmrig:latest
    build:
      context: xmrig-p2pool/.
      args:
        - XMRIG_GIT_TAG=v6.22.0
    container_name: p2pool-xmrig
    networks:
      - p2pool
    privileged: true
    volumes:
      - /dev:/dev:ro
      - /lib/modules:/lib/modules:ro
      - /dev/hugepages:/dev/hugepages:rw
    depends_on:
      - p2pool
    restart: unless-stopped
    healthcheck:
      test: pgrep xmrig > /dev/null && exit 0 || exit 1
      interval: 60s
      retries: 3
      start_period: 60s
      timeout: 5s
    command: >-
      --randomx-1gb-pages
      -o p2pool:3333
      -u p2pool
      --cpu-max-threads-hint=100
      --cpu-priority=2
      --donate-level=1
