name: Lint Dockerfile

on: push

jobs:
  dockerfile-linter:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          config: ".hadolint.yaml"
          dockerfile: "Dockerfile"
          recursive: true
          verbose: true
          failure-threshold: "warning"